#! /bin/sh

sxhkd &
~/dotfiles/bin/launch.sh

if [ $(hostname) = 'calla-bryn-sturgis' ]; then
    bspc monitor DP1 -d 1 3 5 7 9
    bspc monitor HDMI1 -d 2 4 6 8 10
elif [ $(hostname) = 'gilead' ]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width                3
bspc config window_gap                  0

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc config normal_border_color         '#eee8d5'
bspc config active_border_color         '#eee8d5'
bspc config focused_border_color        '#586e75'
