#!/bin/sh

xrdb -load ~/.Xresources

# Setup the keyboard
setxkbmap pl
setxkbmap -option caps:escape
xset r off

PATH="$HOME/dotfiles/bin:$PATH"

# Disable touchpad on ThinkPadX240
TOUCH_PAD="Synaptics TM2927-001"
TOUCHSCREEN="ELAN Touchscreen"

if xinput list | grep "$TOUCH_PAD"; then
    xinput set-prop "$TOUCH_PAD" "libinput Tapping Drag Enabled" 0
fi

export MONITOR_COUNT=$(xrandr | grep ' connected' | wc -l)

# Set the screens
if xrandr | grep eDP1 >/dev/null; then
    if [ "$MONITOR_COUNT" = 2 ]; then
        xrandr --output DP1 --left-of eDP1
    fi

    xbacklight -set 10
    xrandr --dpi 120
    xinput --map-to-output "$TOUCHSCREEN" "eDP1"
else
    xrandr --output DP1 --left-of HDMI1
fi

# Set background color
xsetroot -solid "#eee8d5"

# Autostart
xbanish &
check_mail &
sync_tasks &
sxhkd &

# Start GPG agent
GPG_AGENT_SOCK=$(gpgconf --list-dirs agent-socket)
if [ ! -S $GPG_AGENT_SOCK ]; then
  gpg-agent --daemon >/dev/null 2>&1
fi

export GPG_TTY=$(tty)
echo UPDATESTARTUPTTY | gpg-connect-agent >/dev/null 2>&1

launch_bar

# Setup the desktops
if [ $(hostname) = 'calla-bryn-sturgis' ]; then
    bspc monitor DP1 -d 1 3 5 7 9
    bspc monitor HDMI1 -d 2 4 6 8 10

    temp &
elif [ $(hostname) = 'gilead' ]; then
    if [ "$MONITOR_COUNT" = 2 ]; then
        bspc monitor DP1 -d 1 3 5 7 9
        bspc monitor eDP1 -d 2 4 6 8 10
    else
        bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    fi
fi

# BSPWM config
bspc config border_width                3
bspc config window_gap                  0

bspc config split_ratio                 0.52
bspc config borderless_monocle          false
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc config normal_border_color         '#eee8d5'
bspc config active_border_color         '#eee8d5'
bspc config focused_border_color        '#586e75'
